set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR ARM)

set(TOOLCHAIN_PREFIX arm-none-eabi-)

# Windows 本机构建：使用本地安装路径
# Linux/CI 构建：TOOLCHAIN_DIR 留空，直接使用 PATH 中的工具链
if(WIN32 AND (NOT DEFINED TOOLCHAIN_DIR OR TOOLCHAIN_DIR STREQUAL ""))
    set(TOOLCHAIN_DIR "C:/Program Files (x86)/GNU Arm Embedded Toolchain/10 2021.10")
endif()

if(DEFINED TOOLCHAIN_DIR AND NOT TOOLCHAIN_DIR STREQUAL "")
    set(TOOLCHAIN_BIN "${TOOLCHAIN_DIR}/bin/")
    if(WIN32)
        set(EXE_EXT ".exe")
    else()
        set(EXE_EXT "")
    endif()
    set(CMAKE_C_COMPILER   "${TOOLCHAIN_BIN}${TOOLCHAIN_PREFIX}gcc${EXE_EXT}")
    set(CMAKE_CXX_COMPILER "${TOOLCHAIN_BIN}${TOOLCHAIN_PREFIX}g++${EXE_EXT}")
    set(CMAKE_ASM_COMPILER "${TOOLCHAIN_BIN}${TOOLCHAIN_PREFIX}gcc${EXE_EXT}")
    set(CMAKE_AR           "${TOOLCHAIN_BIN}${TOOLCHAIN_PREFIX}ar${EXE_EXT}")
    set(CMAKE_OBJCOPY      "${TOOLCHAIN_BIN}${TOOLCHAIN_PREFIX}objcopy${EXE_EXT}")
    set(CMAKE_OBJDUMP      "${TOOLCHAIN_BIN}${TOOLCHAIN_PREFIX}objdump${EXE_EXT}")
    set(CMAKE_SIZE         "${TOOLCHAIN_BIN}${TOOLCHAIN_PREFIX}size${EXE_EXT}")
    set(CMAKE_FIND_ROOT_PATH "${TOOLCHAIN_DIR}")
else()
    # CI/Linux：工具在 PATH 上，只用前缀即可
    set(CMAKE_C_COMPILER   ${TOOLCHAIN_PREFIX}gcc)
    set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}g++)
    set(CMAKE_ASM_COMPILER ${TOOLCHAIN_PREFIX}gcc)
    set(CMAKE_AR           ${TOOLCHAIN_PREFIX}ar)
    set(CMAKE_OBJCOPY      ${TOOLCHAIN_PREFIX}objcopy)
    set(CMAKE_OBJDUMP      ${TOOLCHAIN_PREFIX}objdump)
    set(CMAKE_SIZE         ${TOOLCHAIN_PREFIX}size)
endif()

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
